[package]
name = "mcp-deadmanssnitch"
version = "0.1.0"
description = "Model Context Protocol server for Dead Man's Snitch"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
deadmanssnitch = { path = "../deadmanssnitch", version = "0.1.0" }
rmcp.workspace = true
