[package]
name = "deadmanssnitch"
version = "0.1.0"
description = "Typed client for the Dead Man's Snitch API"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true
